version: '3.8'

services:
  nginx:
    image: hyomin0401/myimg:blue
    ports: 
      - "8000:80"
    deploy:
      replicas: 3
      placement:
        constraints: [node.role==worker]

networks:
  default:
